# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13-buster-node-browsers-legacy

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
#       - run: go get -v -t -d ./...
      - setup_remote_docker
      - run: sudo docker build -t idirall22/gateway:v1 .

      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

      - run: docker push idirall22/gateway:v1

      
